# Generated by Django 3.1.6 on 2021-02-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='register_number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
