# Generated by Django 3.1.6 on 2021-02-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20210209_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='register_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
