# Generated by Django 3.1.6 on 2021-02-09 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate', '0003_auto_20210209_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalprofile',
            options={'verbose_name_plural': 'hospital profile'},
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='is_user',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='hospital',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
