# Generated by Django 3.1.6 on 2021-02-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_userprofile_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalprofile',
            options={},
        ),
    ]
