# Generated by Django 3.1.6 on 2021-02-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_auto_20210210_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_user',
        ),
    ]
