# Generated by Django 3.1.6 on 2021-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_remove_userprofile_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(default='default.jpeg', upload_to='pics'),
        ),
    ]
