# Generated by Django 3.1.6 on 2021-02-10 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.IntegerField()),
                ('blood_type', models.CharField(max_length=20)),
                ('blood_units', models.IntegerField(null=True)),
                ('target_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hospital_name', models.CharField(max_length=100, null=True)),
                ('hospital_location', models.CharField(max_length=100, null=True)),
                ('patient_address', models.TextField(null=True)),
                ('purpose', models.TextField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
