# Generated by Django 3.1.6 on 2021-02-10 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_a_positive', models.IntegerField(default=0, null=True)),
                ('w_a_negative', models.IntegerField(default=0, null=True)),
                ('w_b_positive', models.IntegerField(default=0, null=True)),
                ('w_b_negative', models.IntegerField(default=0, null=True)),
                ('w_ab_positive', models.IntegerField(default=0, null=True)),
                ('w_ab_negative', models.IntegerField(default=0, null=True)),
                ('w_o_positive', models.IntegerField(default=0, null=True)),
                ('w_o_negative', models.IntegerField(default=0, null=True)),
                ('b_a_positive', models.IntegerField(default=0, null=True)),
                ('b_a_negative', models.IntegerField(default=0, null=True)),
                ('b_b_positive', models.IntegerField(default=0, null=True)),
                ('b_b_negative', models.IntegerField(default=0, null=True)),
                ('b_ab_positive', models.IntegerField(default=0, null=True)),
                ('b_ab_negative', models.IntegerField(default=0, null=True)),
                ('b_o_positive', models.IntegerField(default=0, null=True)),
                ('b_o_negative', models.IntegerField(default=0, null=True)),
                ('RDP', models.IntegerField(default=0, null=True)),
                ('SDP', models.IntegerField(default=0, null=True)),
                ('FFP', models.IntegerField(default=0, null=True)),
                ('CRYO', models.IntegerField(default=0, null=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
