# Generated by Django 3.1.6 on 2021-02-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_requestblood'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestblood',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
